<?php

/**
 * @file
 * The private_message_messenger.module file.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function private_message_messenger_theme($existing, $type, $theme, $path) {
  return [
    'pmm_thread' => [
      'variables' => [
        'fallback_picture' => NULL,
        'base_path' => '/',
        'thread_actions' => TRUE,
        'welcome_text' => NULL,
        'strings' => [
          'inbox' => NULL,
          'message_placeholder' => NULL,
          'username_placeholder' => NULL,
          'send' => NULL,
          'delete' => NULL,
        ],
      ],
    ],
    'pmm_threads' => [
      'variables' => [
        'strings' => [
          'new_message' => NULL,
          'loading' => NULL,
        ],
      ],
    ],
    'pmm_thread_teaser' => [
      'variables' => [
        'fallback_picture' => NULL,
        'id_suffix' => NULL,
      ],
    ],
    'pmm_recent' => [
      'variables' => [
        'strings' => [
          'link' => NULL,
          'more' => NULL,
          'loading' => NULL,
        ],
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_pmm_threads().
 */
function template_preprocess_pmm_threads(&$variables) {
  $variables['#attached']['library'][] = 'private_message_messenger/threads';
  $variables['strings'] = [
    'new_message' => t('New Message'),
    'loading' => t('Loading...'),
  ];
}

/**
 * Implements hook_preprocess_pmm_thread().
 */
function template_preprocess_pmm_thread(&$variables) {
  $variables['#attached']['library'][] = 'private_message_messenger/thread';
  $variables['fallback_picture'] = _private_message_messenger_fallback_picture();
  $variables['base_path'] = base_path();
  $variables['strings'] = [
    'inbox' => t('‹ Inbox'),
    'message_placeholder' => t('Type a message'),
    'username_placeholder' => t('Type a username'),
    'send' => t('Send'),
    'delete' => t('Delete thread'),
  ];
}

/**
 * Implements hook_preprocess_pmm_thread().
 */
function template_preprocess_pmm_thread_teaser(&$variables) {
  $variables['fallback_picture'] = _private_message_messenger_fallback_picture();
}

/**
 * Implements hook_preprocess_pmm_recent().
 */
function template_preprocess_pmm_recent(&$variables) {
  $helper = \Drupal::service('private_message_messenger.messenger');
  $variables['#attached']['library'][] = 'private_message_messenger/recent';
  $variables['url'] = $helper->getMessengerPath();
  $variables['strings'] = [
    'link' => t('Messages'),
    'more' => t('All Messages'),
    'loading' => t('Loading...'),
  ];
}

/**
 * Get the fallback image.
 *
 * @return string
 *   Path to the default image.
 */
function _private_message_messenger_fallback_picture() {
  $img = base_path() . drupal_get_path('module', 'private_message_messenger') . '/images/default-profile.jpg';
  \Drupal::moduleHandler()->alter('private_message_messenger_fallback_picture', $img);
  return $img;
}

/**
 * A wrapper to return messenger settings.
 *
 * @return array
 *   Array of settings for drupalSettings.
 */
function _private_message_messenger_get_settings() {
  $helper = \Drupal::service('private_message_messenger.messenger');
  return $helper->getSettings();
}

/**
 * Implements hook_entity_extra_field_info().
 */
function private_message_messenger_entity_extra_field_info() {
  $fields = [];

  $user_bundles = \Drupal::entityManager()->getBundleInfo('user');
  foreach (array_keys($user_bundles) as $bundle) {
    $fields['user'][$bundle]['display']['private_message_messenger_link'] = [
      'label' => t('Private message messenger thread link'),
      'description' => t('Displays a link to send a private message to the user via Messenger'),
      'visible' => FALSE,
    ];
  }

  return $fields;
}

/**
 * Implements hook_user_view().
 */
function private_message_messenger_user_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($display->getComponent('private_message_messenger_link')) {
    $current_user = \Drupal::currentUser();
    if ($current_user->hasPermission('use private messaging system') && $current_user->id() != $entity->id()) {
      $path = 'new-' . $entity->id();
      $build['private_message_messenger_link'] = [
        '#type' => 'link',
        '#url' => Url::fromRoute('private_message_messenger.messenger', [], ['fragment' => $path]),
        '#title' => t('Send private message'),
        '#attributes' => ['class' => ['private_message_link']],
        '#prefix' => '<div class="pmm_link_wrapper">',
        '#suffix' => '</div>',
      ];
    }
  }
}

function private_message_messenger_library_info_alter(&$libraries, $extension) {
  $use_timeago_cdn = \Drupal::config('private_message_messenger.settings')->get('timeago_cdn');

  if ($use_timeago_cdn && $extension == 'private_message_messenger') {
    $libraries['init']['dependencies'][] = 'private_message_messenger/timeago_cdn';
  }
}